---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - php
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
    - f38fa3d41f1f3609dd2ef2dcbedeba77
    - 2df635fa2a72329ab36ea883a12159b7
  shellcheck:
    enabled: true
    checks:
      SC2034:
        enabled: false
ratings:
  paths:
  - "**.rb"
  - "**.sh"
exclude_paths: []
